### ISSUE TITLE
Create Workflow to Deploy and Test todo-python-mongo-swa-func

### ISSUE THREAD

**Issue by hattan** [Azure/benchpress#264]
As a developer, I would like a GitHub workflow to deploy and tear down todo-python-mongo-swa-func, so that I can have a template pipeline to use with BenchPress.

[todo-python-mongo-swa-func](https://github.com/Azure-Samples/todo-python-mongo-swa-func)

Acceptance Criteria:

- [ ] It should deploy Todo-Python-Mongo-SWA app .
- [ ] It should execute any tests (if available), not writing tests will be a different issue.
- [ ] It should tear down the deployment

Ideally the deployment would happen in the workflow and not via BenchPress itself. This is an example of an end to end testing scenario. In the future , spin up / tear down tests will be added focused on individual Bicep Module life cycles.
