### ISSUE TITLE
Create CI/CD Pipeline to ensure helpers are tested

### ISSUE THREAD

**Issue by msha1026** [Azure/benchpress#73]
Create a basic CI/CD pipeline to lint, unit test, and deploy to PSGallery

Acceptance Criteria:
- [x] PR/CI Pipeline (Github Actions) to lint (and unit test if existing) open pull requests to the repository
- [x] CD Pipeline (Github Action) to deploy to PSGallery
- [ ] Fully functioning CI/CD (private [Sprint 1] + public [Sprint 2])

**Comment by msha1026** [comment]
May be a duplicate of #83 #85 and #84

**Comment by msha1026** [comment]
Yup, makes sense. Just adding further comments/descriptions to Issues so that we can decide how to parent, mark as dup, and/ or break them down during tomorrow's sessions.
